apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-compose
spec: 
  selector:
    matchLabels:
      app: spring-compose
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-compose
    spec:
      containers:
        - name: spring-compose
          image: bangaru999/customers
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80                    
--- 
apiVersion: v1
kind: Service
metadata: 
  name: springboot-compose
spec:
  selector:
    app: spring-compose
  ports: 
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer